### ISSUE TITLE
Wrong text in "Further Support"

### ISSUE THREAD

**Issue by mareikei** [civilmrcc/claimasylum#5]
Here you can find support 
- if you have just arrived in a European country: ‚welcome2europe.info'
- if a pushback is imminent: call the Alarmphone +334 8651 7161 (http://alarmphone.org/)
- if you have already submitted an asylum application via claimasylum you can access your data here: https://app.claim-asylum.eu/accessdata

**Comment by niczem** [comment]
Where is the "further support part" I think i do not find it.

**Comment by mareikei** [comment]
At the end of the page. First there is the form, then the info, then further support, and there the text is broken.

**Comment by mareikei** [comment]
https://github.com/civilmrcc/claimasylum/assets/57711370/e39c31f2-071b-40da-8963-ce186156231b

**Comment by niczem** [comment]
sorry i did oversee this. also here we need the translations.
