### ISSUE TITLE
Data protection info is missing

### ISSUE THREAD

**Issue by mareikei** [civilmrcc/claimasylum#6]
use the one from civilfleet

**Comment by mareikei** [comment]
https://docs.google.com/document/d/1bj2gTozuUX9PHzloLxjcRm7oOXWhoz_yEVrf2BizvIA/edit

**Comment by niczem** [comment]
As its a separate content it will not be part of the app. We will add a single html which includes all the langues

**Comment by mareikei** [comment]
data protection and terms and conditions will be in the same issue, so closing #7

**Comment by niczem** [comment]
![image](https://github.com/civilmrcc/claimasylum/assets/2991319/09223309-440d-4b2c-a089-bef8d76db73b)

the headings in the google docs file are not correct/uniform, which leads to wrongly parsed text in the html:

![image](https://github.com/civilmrcc/claimasylum/assets/2991319/9fd4132b-c90f-46e1-a10b-530d15fc81e5)

please fix

**Comment by mareikei** [comment]
@niczem should I make it in mardown, e.g. like 
`**7.11 Hosting** ?`

**Comment by niczem** [comment]
It seem to be different kind of headings in the google docs. E.g. "8. Right to complain"  and "7.10 Deletion of data" that needs to be uniform to be parsed properly. I could imagine that one headline is organised by setting the font size to large and the other one is set as "headline 2" or the like. All of the headlines should be formatted as proper headlines.

Just adding the document in markdown would be another possibility.
