### ISSUE TITLE
create checkbox for anonymised statistics

### ISSUE THREAD

**Issue by mareikei** [civilmrcc/claimasylum#8]
need to create a checkbox for the okay:

„I agree that my case is anonymised and used for public statistics“

-> can be next to the "terms & conditions"

![Screenshot_2023-10-15_20-48-59](https://github.com/civilmrcc/claimasylum/assets/57711370/2abc846d-7122-4a0c-9f8c-cd85b8ce5537)

**Comment by mareikei** [comment]
"We will not publish any personal data of you, e.g. your name, email or birthday. We will only save the location, date and outcome/status" of your case. Of course, you have the right to decline this by not clicking the checkbox"

-> like that?

**Comment by mareikei** [comment]
where do you want to write this? @niczem

**Comment by niczem** [comment]
"where do you want to write this? @niczem"
I don't understand the question.

Also the translations are still missing.

**Comment by mareikei** [comment]
I wrote a small text to explain what we are saving! 
If you agree to the text and the other I am happy to translate

**Comment by niczem** [comment]
I am not sure who can approve the text. I just need a text and translations :)

**Comment by mareikei** [comment]
Here is an example of what I mean:
![Vorschlag](https://github.com/civilmrcc/claimasylum/assets/57711370/24bfa3fd-5727-4a3f-b2d3-b6037f2c2862)



**The text used**
Do you agree that your case is anonymised and used for public statistics.
We will not publish any personal data of you, e.g. your name, email or birthday. We might share the location, date and outcome/status of your case with journalists and scientists.

Does this make sense?? is this as we want it? Is this feasible?
